CREATE TABLE IF NOT EXISTS  PROPOSTA (
	ID_PROPOSTA int(11),
	ESTADO varchar(255) not null,
	NUMERO int,
	CPF varchar(255),
	PRIMARY KEY(ID_PROPOSTA),
	UNIQUE(ID_PROPOSTA)
);

ALTER TABLE PROPOSTA MODIFY COLUMN ID_PROPOSTA INT auto_increment;

CREATE TABLE IF NOT EXISTS AUDITORIA (
	ID_AUDITORIA int(11),
    NUMERO_PROPOSTA int,
    ESTADO varchar(255),
    CPF varchar(255),
    DATA_AUD varchar(255),
    DURACAO varchar(255),
    UNIQUE(ID_AUDITORIA)
);

ALTER TABLE AUDITORIA MODIFY COLUMN ID_AUDITORIA INT auto_increment;
